modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
    modId="blueflame" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Blue Flame Burning" #mandatory
    credits="me" #optional
    authors="LobsterJonn" #optional
    description='''
Makes soul fire burn entities with a blue flame instead of regular flames.
'''
[[dependencies.blueflame]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.blueflame]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
